### PR TITLE
Compatibility with Titanium SDK >= 8.0.0

### PR DESCRIPTION
**Pull request by ottopic**
Sooo this pull request escalated a bit. Started with the idea of compiling a dist-version of this module, I did a few things:

- Use 8.0.0.GA to build
- Bump version to 2.0.2 (required by some Utils that are 8.0.0+)
- Removed unused reference to TiUIButtonProxy

### CODE REVIEW

**Comment by viezel** [comment]
great 👍

**Comment by mrtomnguyen** [comment]
any chance this update can be repackaged and released?

**Comment by ottopic** [comment]
Already done, you can find it in dist folder.

Il giorno lun 24 giu 2019 alle 18:44 Tom Nguyen <notifications@github.com>
ha scritto:

**Comment by jasonkneen** [comment]
I'm trying 2.0.0 and still getting this error which is bizarre. Any clues @hansemannn @ottopic as to why this would still be happening? on 8.3.0.GA

```message = "+[TiUtils isIOS6OrGreater]: unrecognized selector sent to class 0x10798da78";```

**Comment by jasonkneen** [comment]
Ahh, apologies -- misread the comment about dist folder as being the releases section -- will try 2.0.2

**Pull request merged**
